In [140]:
import pandas as pd
import numpy as np

In [141]:
df1 = pd.read_csv('airbnbdata30-120final.csv').iloc[:,1:]

df2 = pd.read_csv('airbnbdataabove230.csv').iloc[:,1:]

df3 = pd.read_csv('Sharon_data_121_230.csv').iloc[:,1:]

df = pd.concat([df1, df2], ignore_index = True)

df_final = pd.concat([df, df3], ignore_index = True)

df_final = df.drop_duplicates()

In [142]:
df_final

,price,accommodates,bedrooms,beds,bathrooms,room_type,number_of_reviews,rating,lat,lon,superhost,response_rate
0,Price\r$49 per night,2,1,1.0,1.0,Private room in apartment,554 Reviews,Rating 4.5 out of 5,40.822641,-73.940409,FALSE,100%
1,Price\r$51 per night,2,1,2.0,1.0,Private room in apartment,134 Reviews,Rating 4.5 out of 5,40.791538,-73.942331,FALSE,90%
2,Price\r$47 per night,2,1,1.0,1.0,Private room in apartment,220 Reviews,Rating 4.5 out of 5,40.799565,-73.964680,FALSE,100%
3,Price\r$53 per night,2,1,2.0,1.0,Private room in apartment,78 Reviews,Rating 4 out of 5,40.791416,-73.946641,FALSE,90%
4,Price\r$33 per night,2,studio,1.0,1.0,Private room in apartment,33 Reviews,Rating 4 out of 5,40.783393,-73.951685,FALSE,100%
5,Price\r$39 per night,5,1,3.0,2.0,Private room in house,125 Reviews,Rating 5 out of 5,40.794391,-73.946024,"true,",97%
6,Price\r$50 per night,6,1,3.0,1.0,Private room in apartment,183 Reviews,Rating 4.5 out of 5,40.790244,-73.940635,FALSE,100%
7,Price\r$42 per night,3,1,1.0,1.0,Private room in apartment,86 Reviews,Rating 4.5 out of 5,40.712800,-73.989089,FALSE,100%
8,Price\r$34 per night,4,1,2.0,1.0,Private room in apartment,262 Reviews,Rating 4.5 out of 5,40.810504,-73.925071,FALSE,91%
9,Price\r$49 per night,4,1,2.0,1.0,Private room in apartment,100 Reviews,Rating 4.5 out of 5,40.793912,-73.944316,"true,",97%
10,Price\r$31 per night,2,1,1.0,1.0,Private room in apartment,2 Reviews,no rating,40.783861,-73.953396,FALSE,100%
11,Price\r$38 per night,2,1,1.0,1.0,Private room in apartment,59 Reviews,Rating 4 out of 5,40.757800,-73.992109,FALSE,100%
12,Price\r$49 per night,3,1,3.0,2.0,Private room in house,107 Reviews,Rating 5 out of 5,40.793345,-73.945681,"true,",97%
13,Price\r$40 per night,1,1,1.0,1.0,Private room in apartment,90 Reviews,Rating 5 out of 5,40.829026,-73.947469,FALSE,100%
14,Price\r$50 per night,1,1,1.0,1.0,Shared room in apartment,17 Reviews,Rating 4.5 out of 5,40.763146,-73.989187,FALSE,100%
15,Price\r$49 per night,2,1,1.0,1.0,Private room in apartment,566 Reviews,Rating 4.5 out of 5,40.820853,-73.940246,FALSE,100%
16,Price\r$35 per night,2,1,1.0,1.0,Private room in apartment,59 Reviews,Rating 4 out of 5,40.757800,-73.992109,FALSE,100%
17,Price\r$50 per night,2,1,1.0,1.0,NoneType,NoneType,no rating,40.788284,-73.943853,"true,",no info
18,Price\r$48 per night,3,2,2.0,1.0,Private room in apartment,293 Reviews,Rating 4.5 out of 5,40.797936,-73.932233,FALSE,100%
19,Price\r$50 per night,1,1,1.0,1.0,Private room in apartment,123 Reviews,Rating 4.5 out of 5,40.762753,-73.995250,FALSE,100%
20,Price\r$48 per night,3,1,1.0,1.0,Private room in house,158 Reviews,Rating 4 out of 5,40.768605,-73.931650,FALSE,100%
21,Price\r$49 per night,4,1,3.0,1.0,Private room in apartment,91 Reviews,Rating 4.5 out of 5,40.794281,-73.944325,"true,",97%
22,Price\r$44 per night,2,1,1.0,1.0,Private room in apartment,49 Reviews,Rating 4 out of 5,40.783111,-73.952205,FALSE,100%
23,Price\r$50 per night,1,1,1.0,1.0,Private room in apartment,175 Reviews,Rating 4.5 out of 5,40.762891,-73.994193,FALSE,100%
24,Price\r$40 per night,1,1,1.0,1.0,Private room in apartment,55 Reviews,Rating 5 out of 5,40.818066,-73.954872,FALSE,75%
25,Price\r$44 per night,2,studio,1.0,1.0,Private room in apartment,44 Reviews,Rating 4 out of 5,40.783958,-73.953057,FALSE,100%
26,Price\r$45 per night,2,1,1.0,1.0,Private room in house,152 Reviews,Rating 4 out of 5,40.766590,-73.932750,FALSE,100%
27,Price\r$42 per night,2,1,2.0,1.0,Private room in apartment,67 Reviews,Rating 4 out of 5,40.800550,-73.941015,FALSE,NaN
28,Price\r$40 per night,2,1,1.0,1.0,Private room in apartment,557 Reviews,Rating 4.5 out of 5,40.821243,-73.938382,FALSE,NaN
29,Price\r$45 per night,1,1,1.0,1.0,Private room in apartment,29 Reviews,Rating 5 out of 5,40.793719,-73.934455,FALSE,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2187,"Price\r$2,000 per night",6,3,1.0,3.5,Entire apartment,NoneType,no rating,40.744976,-73.988664,FALSE,NaN
2188,"Price\r$5,000 per night",3,1,2.0,1.0,Entire apartment,2 Reviews,no rating,40.721927,-73.993787,FALSE,NaN
2189,"Price\r$1,485 per night",8,3,5.0,2.0,Entire loft,2 Reviews,no rating,40.722952,-73.997861,FALSE,NaN
2191,"Price\r$2,900 per night",6,1,1.0,1.0,Entire townhouse,NoneType,no rating,40.779777,-73.975982,FALSE,NaN
2192,"Price\r$1,000 per night",4,1,2.0,1.0,Entire apartment,NoneType,no rating,40.760027,-73.969691,FALSE,NaN
2193,"Price\r$1,150 per night",6,3,4.0,3.5,Entire apartment,NoneType,no rating,40.717252,-74.006928,FALSE,NaN
2194,"Price\r$1,000 per night",3,studio,1.0,1.0,Entire apartment,3 Reviews,Rating 5 out of 5,40.763473,-73.978002,FALSE,NaN
2195,"Price\r$3,000 per night",1,1,NaN,NaN,Private room in apartment,NoneType,no rating,40.801425,-73.969306,FALSE,NaN
2196,"Price\r$2,250 per night",0,5,7.0,3.5,Entire apartment,NoneType,no rating,40.726051,-74.005724,FALSE,NaN
2198,"Price\r$10,000 per night",4,1,1.0,1.0,Entire apartment,NoneType,no rating,40.772131,-73.986647,FALSE,NaN
2199,"Price\r$1,500 per night",4,2,2.0,2.5,Entire loft,NoneType,no rating,40.722735,-74.010492,FALSE,NaN
2200,"Price\r$2,000 per night",5,2,3.0,2.5,Entire condominium,1 Review,no rating,40.720953,-74.002501,FALSE,NaN
2201,"Price\r$1,170 per night",7,3,3.0,3.0,Entire apartment,NoneType,no rating,40.748675,-73.967339,FALSE,NaN
2202,"Price\r$1,000 per night",4,2,2.0,1.0,Entire apartment,NoneType,no rating,40.759301,-73.991435,FALSE,NaN
2203,"Price\r$1,500 per night",4,2,2.0,2.5,Entire loft,NoneType,no rating,40.722080,-74.002171,FALSE,NaN
2204,"Price\r$1,000 per night",5,4,4.0,3.0,Entire apartment,2 Reviews,no rating,40.787399,-73.973813,FALSE,NaN
2205,"Price\r$1,100 per night",6,3,3.0,3.5,Entire apartment,NoneType,no rating,40.751430,-73.969727,FALSE,NaN
2206,"Price\r$2,000 per night",2,1,1.0,1.0,Private room in apartment,NoneType,no rating,40.760334,-73.990039,FALSE,NaN
2207,"Price\r$1,500 per night",1,studio,1.0,2.0,Entire loft,3 Reviews,no rating,40.756008,-73.989090,FALSE,NaN
2208,"Price\r$1,100 per night",7,4,5.0,3.0,Entire townhouse,NoneType,no rating,40.738369,-74.005860,FALSE,NaN
2209,"Price\r$1,500 per night",6,3,3.0,3.0,Entire loft,2 Reviews,no rating,40.740430,-73.992765,FALSE,NaN
2210,Price\r$980 per night,1,1,1.0,1.0,Private room in apartment,1 Review,no rating,40.801834,-73.963734,FALSE,NaN
2211,Price\r$999 per night,4,2,2.0,2.5,Entire apartment,9 Reviews,Rating 5 out of 5,40.734256,-73.994759,FALSE,NaN
2212,"Price\r$1,500 per night",6,1,1.0,2.0,Entire loft,14 Reviews,Rating 5 out of 5,40.751305,-73.983331,FALSE,NaN
2213,"Price\r$2,500 per night",3,1,1.0,2.0,Entire condominium,4 Reviews,Rating 5 out of 5,40.764546,-73.979586,FALSE,NaN
2214,"Price\r$1,500 per night",6,3,4.0,4.5,NoneType,NoneType,no rating,40.736588,-74.002625,FALSE,no info
2215,"Price\r$2,000 per night",8,2,3.0,2.5,Entire condominium,59 Reviews,Rating 5 out of 5,40.775164,-73.985726,FALSE,NaN
2216,"Price\r$1,000 per night",3,1,1.0,1.0,Entire condominium,44 Reviews,Rating 5 out of 5,40.774279,-73.985938,FALSE,100%
2217,"Price\r$1,650 per night",5,2,3.0,2.0,Entire apartment,13 Reviews,Rating 5 out of 5,40.738811,-73.994391,FALSE,91%
2218,"Price\r$1,000 per night",6,3,4.0,1.5,Entire loft,44 Reviews,Rating 4.5 out of 5,40.747952,-73.991706,FALSE,90%

In [143]:
import re
def extract_price(string):
    pattern = r'[$0-9,]+'
    if re.search(pattern, string):
        price_tmp = re.search(pattern, string).group(0)
        price = re.sub('[$,]','',price_tmp)
        return float(price)
    else:
        return None
    
def num_reviews(string):
    pattern = r'^\d+'
    if re.search(pattern, string):
        return int(re.search(pattern, string).group(0))
    else:
        return 0
    
def superhost(string):
    if string == 'FALSE':
        return 0
    else:
        return 1
    
def rating(string):
    pattern = r'[0-9.]+'
    if re.search(pattern, string):
        return float(re.search(pattern, string).group(0))
    else:
        return 0
    
    
popular_room_type = df_final.groupby('room_type').count()[
    df_final.groupby('room_type').count()['price']>50].iloc[[0,1,2,3,4,6]].index.tolist()
# popular_room_dict = dict(zip(popular_room_type, range(1, len(popular_room_type)+1)))
# popular_room_dict = dict(zip(popular_room_type, range(1, len(popular_room_type)+1)))
def room_type(string):
    if string not in popular_room_type:
        return 'others'
    else:
        return string
# def room_type(string):
#     if string not in popular_room_type:
#         return 0
#     else:
#         return popular_room_dict[string]

In [144]:
popular_room_type

['Entire apartment',
 'Entire condominium',
 'Entire loft',
 'Entire serviced apartment',
 'Entire townhouse',
 'Private room in apartment']

In [145]:
df_final['price'] = df_final['price'].apply(lambda p: extract_price(p))
df_final['number_of_reviews'] = df_final['number_of_reviews'].apply(lambda x: num_reviews(x))
df_final['superhost'] = df_final['superhost'].apply(lambda x:superhost(x))
df_final['rating'] = df_final['rating'].apply(lambda x: rating(x))
df_final['room_type'] = df_final['room_type'].apply(lambda x: room_type(x))

/Users/mac/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/mac/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/mac/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/mac/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/mac/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [147]:
df_final = pd.get_dummies(df_final, columns = ['bedrooms'], prefix = ['bedrooms'])
df_final = pd.get_dummies(df_final, columns = ['room_type'], prefix = ['room_type'])

In [149]:
df_final.head(10)

,price,accommodates,beds,bathrooms,number_of_reviews,rating,lat,lon,superhost,response_rate,...,bedrooms_7,bedrooms_8,bedrooms_studio,room_type_Entire apartment,room_type_Entire condominium,room_type_Entire loft,room_type_Entire serviced apartment,room_type_Entire townhouse,room_type_Private room in apartment,room_type_others
0,49.0,2,1.0,1.0,554,4.5,40.822641,-73.940409,0,100%,...,0,0,0,0,0,0,0,0,1,0
1,51.0,2,2.0,1.0,134,4.5,40.791538,-73.942331,0,90%,...,0,0,0,0,0,0,0,0,1,0
2,47.0,2,1.0,1.0,220,4.5,40.799565,-73.964680,0,100%,...,0,0,0,0,0,0,0,0,1,0
3,53.0,2,2.0,1.0,78,4.0,40.791416,-73.946641,0,90%,...,0,0,0,0,0,0,0,0,1,0
4,33.0,2,1.0,1.0,33,4.0,40.783393,-73.951685,0,100%,...,0,0,1,0,0,0,0,0,1,0
5,39.0,5,3.0,2.0,125,5.0,40.794391,-73.946024,1,97%,...,0,0,0,0,0,0,0,0,0,1
6,50.0,6,3.0,1.0,183,4.5,40.790244,-73.940635,0,100%,...,0,0,0,0,0,0,0,0,1,0
7,42.0,3,1.0,1.0,86,4.5,40.712800,-73.989089,0,100%,...,0,0,0,0,0,0,0,0,1,0
8,34.0,4,2.0,1.0,262,4.5,40.810504,-73.925071,0,91%,...,0,0,0,0,0,0,0,0,1,0
9,49.0,4,2.0,1.0,100,4.5,40.793912,-73.944316,1,97%,...,0,0,0,0,0,0,0,0,1,0

In [150]:
df_new = df_final.drop(columns = ['response_rate','lat','lon'])

In [151]:
df_new = df_new.dropna(how = 'any', axis = 0)

In [152]:
df_new.head(8)

,price,accommodates,beds,bathrooms,number_of_reviews,rating,superhost,bedrooms_1,bedrooms_2,bedrooms_3,...,bedrooms_7,bedrooms_8,bedrooms_studio,room_type_Entire apartment,room_type_Entire condominium,room_type_Entire loft,room_type_Entire serviced apartment,room_type_Entire townhouse,room_type_Private room in apartment,room_type_others
0,49.0,2,1.0,1.0,554,4.5,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1,51.0,2,2.0,1.0,134,4.5,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
2,47.0,2,1.0,1.0,220,4.5,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,53.0,2,2.0,1.0,78,4.0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
4,33.0,2,1.0,1.0,33,4.0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
5,39.0,5,3.0,2.0,125,5.0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
6,50.0,6,3.0,1.0,183,4.5,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
7,42.0,3,1.0,1.0,86,4.5,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0

## Train Linear Regression Model

In [157]:
from sklearn.model_selection import train_test_split
X = df_new.iloc[:, 1:]
y = df_new['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.20, random_state=42)

In [158]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)
pred_price = reg.predict(X_test)

In [98]:
# from sklearn.preprocessing import PolynomialFeatures
# poly = PolynomialFeatures(2)
# X_train_poly = poly.fit_transform(X_train)

# from sklearn.linear_model import LinearRegression
# reg_poly = LinearRegression().fit(X_train_poly, y_train)
# X_test_poly = poly.fit_transform(X_test)
# pred_price = reg_poly.predict(X_test_poly)

In [159]:
X_test['pred_price'] = pred_price
X_test['actual_price'] = y_test

/Users/mac/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/mac/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [160]:
X_test

,accommodates,beds,bathrooms,number_of_reviews,rating,superhost,bedrooms_1,bedrooms_2,bedrooms_3,bedrooms_4,...,bedrooms_studio,room_type_Entire apartment,room_type_Entire condominium,room_type_Entire loft,room_type_Entire serviced apartment,room_type_Entire townhouse,room_type_Private room in apartment,room_type_others,pred_price,actual_price
2061,4,1.0,1.0,0,0.0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,572.878852,900.0
29,1,1.0,1.0,29,5.0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,83.321199,45.0
220,2,1.0,2.0,4,5.0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,295.007808,38.0
1014,3,2.0,1.0,12,5.0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,257.615454,250.0
615,2,1.0,1.0,0,0.0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,366.143783,85.0
1684,5,2.0,2.0,19,4.5,0,0,1,0,0,...,0,0,0,0,1,0,0,0,501.446064,399.0
1306,4,3.0,1.0,80,5.0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,207.967346,298.0
52,1,1.0,1.0,15,5.0,1,1,0,0,0,...,0,0,0,0,0,0,0,1,195.013271,42.0
710,5,3.0,1.0,78,4.0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,269.077670,100.0
689,2,1.0,1.0,24,5.0,1,1,0,0,0,...,0,0,0,0,0,0,0,1,213.454664,100.0
1282,9,7.0,1.0,6,5.0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,208.771049,319.0
913,2,1.0,1.0,150,5.0,1,1,0,0,0,...,0,0,0,0,0,0,0,1,129.800286,115.0
975,6,5.0,1.0,0,0.0,1,0,1,0,0,...,0,0,0,0,0,0,0,1,448.922192,249.0
1336,8,3.0,2.0,8,4.5,0,0,0,1,0,...,0,1,0,0,0,0,0,0,482.434425,295.0
1499,4,2.0,1.0,4,5.0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,391.041412,370.0
1687,6,3.0,2.0,27,5.0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,412.213648,399.0
198,1,1.0,1.0,2,0.0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,480.778598,40.0
112,1,1.0,1.0,69,4.5,0,1,0,0,0,...,0,0,0,0,0,0,0,1,221.058831,32.0
72,5,1.0,1.0,80,5.0,1,1,0,0,0,...,0,0,0,0,0,0,0,1,249.525058,35.0
1248,8,5.0,3.0,11,5.0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,942.801362,300.0
597,2,1.0,2.0,21,4.0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,471.930894,90.0
1645,0,5.0,3.5,37,5.0,1,0,0,1,0,...,0,0,0,1,0,0,0,0,676.046933,550.0
1460,3,1.0,1.5,49,5.0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,341.878633,349.0
802,2,1.0,1.0,101,4.5,0,1,0,0,0,...,0,0,0,0,0,0,1,0,83.850612,95.0
1053,8,4.0,1.0,34,4.5,0,0,0,1,0,...,0,1,0,0,0,0,0,0,268.295371,249.0
231,2,1.0,1.0,5,4.5,0,1,0,0,0,...,0,0,0,0,0,0,1,0,147.587281,45.0
311,3,2.0,1.0,107,4.5,0,1,0,0,0,...,0,0,0,0,0,0,1,0,78.078550,75.0
658,1,1.0,1.0,10,5.0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,95.935748,80.0
2057,6,3.0,1.0,0,0.0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,483.477473,600.0
653,2,1.0,1.0,63,5.0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,85.164501,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,6,2.0,1.0,29,4.5,0,0,1,0,0,...,0,1,0,0,0,0,0,0,328.316651,600.0
1154,3,1.0,1.0,15,5.0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,241.133903,255.0
670,3,2.0,1.0,143,4.5,0,1,0,0,0,...,0,1,0,0,0,0,0,0,191.843887,119.0
1194,8,4.0,2.0,51,5.0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,456.889893,300.0
1922,2,1.0,1.0,0,0.0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,484.955519,685.0
963,6,3.0,1.0,37,5.0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,293.119896,255.0
45,4,2.0,1.0,155,5.0,1,1,0,0,0,...,0,0,0,0,0,0,1,0,8.729484,52.0
1792,2,7.0,3.0,4,5.0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,380.525581,500.0
1642,8,5.0,2.0,123,4.5,0,0,0,0,1,...,0,0,0,0,0,0,0,1,570.075875,400.0
306,2,1.0,1.0,47,5.0,1,1,0,0,0,...,0,0,0,0,0,0,1,0,57.805052,55.0
1025,5,2.0,1.0,64,5.0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,231.229829,240.0
78,1,2.0,1.0,110,4.5,0,1,0,0,0,...,0,0,0,0,0,0,0,1,167.632736,49.0
215,2,1.0,1.0,7,4.5,0,1,0,0,0,...,0,0,0,0,0,0,1,0,146.259434,45.0
1603,5,2.0,1.0,6,5.0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,295.254980,350.0
1487,0,4.0,4.0,4,3.5,0,0,0,1,0,...,0,1,0,0,0,0,0,0,652.725290,375.0
842,2,1.0,1.0,80,4.5,0,1,0,0,0,...,0,1,0,0,0,0,0,0,235.459597,99.0
1828,6,1.0,2.0,0,0.0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,922.962860,895.0
1207,4,2.0,1.0,8,5.0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,388.385717,300.0
450,4,1.0,1.0,121,4.5,1,0,0,0,0,...,1,1,0,0,0,0,0,0,197.522280,89.0
1468,3,1.0,1.0,109,4.5,0,1,0,0,0,...,0,1,0,0,0,0,0,0,240.622517,345.0
417,3,1.0,1.0,100,4.5,0,1,0,0,0,...,0,0,0,0,0,0,1,0,108.931242,55.0
1562,0,6.0,1.0,7,4.5,0,0,1,0,0,...,0,1,0,0,0,0,0,0,91.601829,350.0
30,3,2.0,1.0,63,5.0,1,1,0,0,0,...,0,0,0,0,0,0,0,1,185.773122,50.0
1243,6,3.0,1.0,86,5.0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,468.870452,319.0
1716,8,3.0,2.0,95,4.5,0,0,0,1,0,...,0,1,0,0,0,0,0,0,424.673069,399.0
1106,3,2.0,1.0,16,4.5,0,1,0,0,0,...,0,1,0,0,0,0,0,0,276.162189,265.0
893,4,2.0,1.0,77,4.5,0,1,0,0,0,...,0,1,0,0,0,0,0,0,260.079553,120.0
2163,5,3.0,5.0,0,0.0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1141.748017,1500.0
818,4,2.0,1.0,78,4.5,0,1,0,0,0,...,0,1,0,0,0,0,0,0,259.415629,115.0
623,4,3.0,1.0,91,4.5,0,0,0,0,0,...,1,0,0,0,0,0,0,1,205.724543,89.0

In [159]:
df_final.groupby('room_type').count()[df_final.groupby('room_type').count()['price']>50]

,price,accommodates,bedrooms,beds,bathrooms,number_of_reviews,rating,lat,lon,superhost,response_rate
room_type,,,,,,,,,,,
Entire apartment,887,896,896,896,896,896,896,896,896,896,596
Entire condominium,84,84,84,84,84,84,84,84,84,84,57
Entire loft,120,120,120,120,120,120,120,120,120,120,90
Entire serviced apartment,88,89,89,89,89,89,89,89,89,89,65
Entire townhouse,65,65,65,65,65,65,65,65,65,65,48
NoneType,89,89,89,89,89,89,89,89,89,89,89
Private room in apartment,537,539,539,538,534,539,539,539,539,539,347

In [161]:
reg.coef_

array([  24.41670586,  -26.20522677,  170.67181265,   -0.66392364,
        -47.83041845,  -37.98222735, -189.44901132, -201.91365927,
       -255.03827945,  -41.34793826,  -41.56947812,  472.20157074,
       -154.85960553,  622.99304474, -211.01664353,  -89.45779626,
         16.95284653,  177.04231534,  -69.22272667,  278.55476158,
       -227.12438457,  -86.74501596])

In [180]:
popular_room_dict

{'Entire apartment': 1,
 'Entire condominium': 2,
 'Entire loft': 3,
 'Entire serviced apartment': 4,
 'Entire townhouse': 5,
 'Private room in apartment': 6}

In [162]:
df_new.columns[1:]

Index(['accommodates', 'beds', 'bathrooms', 'number_of_reviews', 'rating',
       'superhost', 'bedrooms_1', 'bedrooms_2', 'bedrooms_3', 'bedrooms_4',
       'bedrooms_5', 'bedrooms_6', 'bedrooms_7', 'bedrooms_8',
       'bedrooms_studio', 'room_type_Entire apartment',
       'room_type_Entire condominium', 'room_type_Entire loft',
       'room_type_Entire serviced apartment', 'room_type_Entire townhouse',
       'room_type_Private room in apartment', 'room_type_others'],
      dtype='object')

In [163]:
df_final.to_csv('df_preprocessed_data.csv')
df_new.to_csv('df_build_model.csv')